---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    driver:
        box: bento/centos-7.4

suites:
  - name: default
    run_list:
      - recipe[nothingness::default]
      - recipe[nothingness::users]
      - recipe[nothingness::httpd]
      - recipe[nothingness::ls-blog]
      - recipe[nothingness::virtualbox]
      - recipe[nothingness::vagrant]
      - recipe[nothingness::docker]
    attributes:
