---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    driver:
      box: bento/centos-7.4

suites:
  - name: dev
    run_list:
      - recipe[nothingness::default]
      - recipe[nothingness::users]
      - recipe[nothingness::httpd]
      - recipe[nothingness::jenkins]
      - recipe[nothingness::ls-blog]
      - recipe[nothingness::virtualbox]
      - recipe[nothingness::vagrant]
      - recipe[nothingness::docker]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/users
        - test/integration/httpd
        - test/integration/jenkins
        - test/integration/ls-blog
        - test/integration/virtualbox
        - test/integration/vagrant
        - test/integration/docker
    attributes:
      host_context: ".dev"
  - name: admin
    run_list:     
      - recipe[nothingness::default]     
      - recipe[nothingness::users]
      - recipe[nothingness::httpd]
      - recipe[nothingness::jenkins]
      - recipe[export-node::default]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/users
        - test/integration/httpd
        - test/integration/jenkins
    attributes:
      host_context: ""
  - name: build_chain
    run_list:
      - recipe[nothingness::default]
      - recipe[nothingness::users]
      - recipe[nothingness::httpd]
      - recipe[nothingness::ls-blog]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/users
        - test/integration/httpd
        - test/integration/ls-blog
    attributes:
      host_context: ""
