---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    driver:
      box: bento/centos-7.4

suites:
  - name: default
    run_list:
      - recipe[nothingness::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
