---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.5
    driver:
      box: bento/centos-7.5

suites:
  - name: global
    run_list:
      - recipe[nothingness::default]
      - recipe[nothingness::users]
      - recipe[nothingness::security]
      - recipe[nothingness::httpd]
      - recipe[nothingness::jenkins]
      - recipe[nothingness::ls-blog]
      - recipe[nothingness::virtualbox]
      - recipe[nothingness::vagrant]
      - recipe[nothingness::docker]
      - recipe[nothingness::export-attributes]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/users
        - test/integration/security
        - test/integration/httpd
        - test/integration/jenkins
        - test/integration/ls-blog
        - test/integration/virtualbox
        - test/integration/vagrant
        - test/integration/docker
    attributes:
      host_context: ".dev"
