name 'nothingness'
maintainer 'Christos Tsagkournis'
maintainer_email 'chrtsago@yahoo.gr'
license 'All Rights Reserved'
description 'Installs/Configures chef'
long_description 'Installs/Configures chef'
version '0.9.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/ctsag/chef/issues'
source_url 'https://github.com/ctsag/chef'
