pipeline {
  agent any

  environment {
    cookbookDir = 'cookbooks/nothingness/'
  }

  stages {
    stage('Lint Tests') {
      parallel {
        stage('cookstyle') {
          steps {
            sh 'cookstyle -DES -f h ${cookbookDir} > cookstyle_report.html'
          }
        }
        stage('foodcritic') {
          steps {
            sh 'foodcritic ${cookbookDir}'
          }
        }
      }
    }
    stage('Unit Tests') {
      parallel {
        stage('rspec') {
          steps {
            dir(cookbookDir) {
              sh 'chef exec rspec -f d spec/unit/recipes/*'
            }
          }
        }
      }
    }
  }
}
